### ISSUE TITLE
Make a photo upload 

### ISSUE THREAD

**Issue by RuslanKuchmynda** [ezbir/ezbir-fe#30]
### Зробити так щоб коли нажимаєш на свою аватарку можна було загрузити нову аватарку для профілю
Всі endpoints по яким робити запити знаходяться тут: [swagger](http://13.60.12.224/swagger-ui/index.html#/)

**Comment by ilyaOlkh** [comment]
![image](https://github.com/user-attachments/assets/c94f3727-b05f-49d9-af9f-c683a2ca79d4)
![image](https://github.com/user-attachments/assets/792a75f5-16e6-4a65-a639-d8f20184a748)

чому мені блокує запит?

**Comment by ilyaOlkh** [comment]
![image](https://github.com/user-attachments/assets/6deca01a-9c02-4ec5-9305-19d3c0b51b2a)
і ще, до якого апі потрібно надсилати зміни, це начебто лише з описом працює

**Comment by ilyaOlkh** [comment]
![image](https://github.com/user-attachments/assets/9b1417e9-52ba-48bf-93f0-46b74bf6f143)
і не зрозуміло як ця апі процює

**Comment by RuslanGren** [comment]
[add cors configuration](https://github.com/ezbir/ezbir-be/issues/5) @ilyaOlkh @RuslanKuchmynda
